name: DS-python-data-analysis
channels: 
- conda-forge
- defaults
dependencies:
- ipython
- jupyter
- matplotlib>2
- mplleaflet
- notebook
- numpy
- pandas=0.21
- plotnine=0.3.0
- pyproj
- python=3.6
- requests
- seaborn
- xlrd
